site:
  name: 'Michael M'
  site: 'https://penqguin.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: 'Michael M'
    template: '%s â€” Portfolio'
  description: 'My Dev Portfolio'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Michael M'
    images:
      - url: '~/assets/images/igloo-logo.svg'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
